# Generated by Django 5.0.2 on 2024-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur_budget',
            name='date_budget',
            field=models.DateField(),
        ),
    ]
