# Generated by Django 5.0.2 on 2024-04-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_alter_valeur_budget_date_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255)),
                ('mmdp', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depense_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=255)),
                ('ligne', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('id_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.valeur_budget')),
            ],
        ),
    ]
