# Generated by Django 5.0.2 on 2024-04-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_utilisateurs_depense_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='mmdp',
            new_name='mdp',
        ),
    ]
