# Generated by Django 5.0.2 on 2024-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0004_rename_mmdp_utilisateurs_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense_budget',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
