# Generated by Django 5.0.2 on 2024-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0005_depense_budget_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur_budget',
            name='budget_balence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valeur_budget',
            name='budget_solde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valeur_budget',
            name='budget_initial',
            field=models.IntegerField(default=0),
        ),
    ]
