# Generated by Django 5.0.2 on 2024-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_valeur_budget_budget_balence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_valid_comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
