# Generated by Django 5.0.2 on 2024-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0007_code_valid_comptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense_budget',
            name='id_budget',
        ),
    ]
