# Generated by Django 5.0.2 on 2024-04-23 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_remove_depense_budget_id_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense_budget',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='depense_budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
