# Generated by Django 5.0.2 on 2024-04-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0010_alter_valeur_budget_date_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depense_budget',
            old_name='time',
            new_name='times',
        ),
    ]
