# Generated by Django 5.0.2 on 2024-04-23 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0011_rename_time_depense_budget_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur_budget',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
