# Generated by Django 5.0.2 on 2024-04-23 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0012_valeur_budget_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur_budget',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
