# Generated by Django 5.0.2 on 2024-04-23 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0013_alter_valeur_budget_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense_budget',
            name='times',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
