# Generated by Django 5.0.2 on 2024-04-23 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0015_alter_depense_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense_budget',
            name='obs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='depense_budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
