# Generated by Django 5.0.2 on 2024-04-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0016_depense_budget_obs_alter_depense_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense_budget',
            name='users_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Budget.utilisateurs'),
        ),
    ]
