# Generated by Django 5.0.2 on 2024-04-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0017_depense_budget_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense_budget',
            name='users_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Budget.utilisateurs'),
        ),
    ]
