# Generated by Django 5.0.2 on 2024-04-24 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0018_alter_depense_budget_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='numero_telephone',
            field=models.CharField(default='0321234567', max_length=10, validators=[django.core.validators.RegexValidator('^(032|033|034|038)\\d{7}$', message='Veuillez entrer un numéro de téléphone valide.')]),
        ),
    ]
