# Generated by Django 5.0.2 on 2024-04-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0019_utilisateurs_numero_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurs',
            old_name='numero_telephone',
            new_name='contact',
        ),
    ]
